# Generated by Django 3.0.4 on 2020-04-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('category', models.CharField(max_length=100)),
                ('releasedate', models.DateField()),
                ('description', models.TextField()),
                ('productphoto', models.ImageField(default='products/default_product.jpg', upload_to='products')),
            ],
        ),
    ]
