# Generated by Django 3.0.4 on 2020-04-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productphoto',
            field=models.ImageField(default='products/product_default.jpg', upload_to='products'),
        ),
    ]
